version: '3'

vars:
  PORT: 3000
  MINTLIFY_VERSION: latest

tasks:
  # Installation
  install:
    desc: "Install Mintlify CLI globally"
    cmds:
      - npm install -g mintlify@{{.MINTLIFY_VERSION}}
    status:
      - command -v mintlify

  # Development server
  preview:
    desc: "Start Mintlify development server"
    cmds:
      - mintlify dev
    deps:
      - install

  build:
    desc: "Build documentation for production"
    cmds:
      - mintlify build
    deps:
      - install

  check:
    desc: "Check documentation for broken links and errors"
    cmds:
      - mintlify broken-links
    deps:
      - install

  # OpenAPI generation
  openapi:
    desc: "Regenerate OpenAPI specification from API code"
    dir: ../api
    cmds:
      - .venv/bin/python generate_openapi.py
      - cp openapi.json ../docs/openapi.json
      - cp openapi.yaml ../docs/openapi.yaml
      - echo "✓ OpenAPI specification updated in docs/"

  # Cleanup
  clean:
    desc: "Clean build artifacts and cache"
    cmds:
      - rm -rf .mintlify
      - rm -rf node_modules
      - rm -f package-lock.json
      - echo "✅ Cleaned build artifacts"

  # Default task
  default:
    desc: "Show available tasks"
    cmds:
      - task --list
